/* auto-generated by OHOS-RS */
/* eslint-disable */

/**
  * @author <a href="mailto:angcyo@126.com">angcyo</a>
  * @date 2026-03-17
  *
  * https://napi.rs/docs/concepts/values
  * 测试布尔类型的参数传输
  * @return 取反
  */
export declare function testBool(value: boolean): boolean

/**
  * 测试字节缓冲类型的参数传输
  * - https://ohos.rs/docs/more/buffer
  */
export declare function testBuffer(buf: ArrayBuffer): ArrayBuffer

/** 测试字节类型的参数传输 */
export declare function testBytes(value: Array<number>): Array<number>

/** 测试双精度浮点类型的参数传输 */
export declare function testDouble(value: number): number

/** 测试整数类型的参数传输 */
export declare function testInt(value: number): number

/** 测试字符串类型的参数传输 */
export declare function testString(value: string): string

