#!/bin/bash

rustup target add aarch64-unknown-linux-ohos
rustup target add armv7-unknown-linux-ohos
rustup target add x86_64-unknown-linux-ohos

# https://ohos.rs/docs/basic/quick-start.html#%E5%AE%89%E8%A3%85
# 需要配置 OHOS_NDK_HOME / `export OHOS_NDK_HOME=/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony`
cargo install ohrs